#!/bin/sh
echo "Post installation process started"

echo "Install binary symlink"
ln -si "/Library/InstructLab/InstructLab.app/Contents/MacOS/InstructLab" /usr/local/bin/ilab

/usr/local/bin/ilab-bar &
echo "Post installation process finished"
